### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by dedsresende** [bgschiller/postgres_kernel#12]
Hi, I've been trying to use the PostgreSQL kernel but i am having the following issue:
![screenshot from 2018-02-19 11-02-33](https://user-images.githubusercontent.com/15621045/36372169-7f1e627e-1564-11e8-8835-6d37ed547fdb.png)
Error: Unable to connect to a database at "".
  Perhaps you need to set a connection string with
  -- connection: <connection string here>
I am not sure If I am skipping a step or if there is really an issue.
Thank you very much for your attention!

**Comment by raviolli77** [comment]
In order to run the kernel from the notebook you need a connection string. 

My friends utilized this kernel in a workshop you can find the format [here](https://github.com/timothydnguyen/sql_de_mayo/blob/master/beginner/beginner_notebook.ipynb).

**Comment by bgschiller** [comment]
I added some docs to the README on this.
