### ISSUE TITLE
pip installable

### ISSUE THREAD

**Issue by haraldschilly** [bgschiller/postgres_kernel#3]
quick and dirty solution: `pip install git+https://github.com/bgschiller/postgres_kernel.git`

**Comment by insightfulprogrammer** [comment]
This worked. I am getting this error on starting `jupyter notebook`.

```
(::1) 15.17ms referer=http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=postgres
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3: Error while finding spec for 'postgres_kernel.__main__' (<class 'ImportError'>: No module named 'version'); 'postgres_kernel' is a package and cannot be directly executed
```

**Comment by lnxbil** [comment]
Thank you!

**Comment by nikoskaragiannakis** [comment]
I sent a PR that solves the issue https://github.com/bgschiller/postgres_kernel/pull/9
Could you have a look?

**Comment by nikoskaragiannakis** [comment]
I sent a PR *(https://github.com/bgschiller/postgres_kernel/pull/9) that solves this issue. 
Could you have a look?

**Comment by mhoangvslev** [comment]
https://packaging.python.org/tutorials/packaging-projects/

**Comment by bgschiller** [comment]
Now pip installable!
