### ISSUE TITLE
execution seems to stick if output has international characters

### ISSUE THREAD

**Issue by DrXyzzy** [bgschiller/postgres_kernel#4]
Try selecting when a value returned contains one of ãáóê etc. and the * appears indicating execution, but no output appears.

![screenshot 2017-03-30 15 52 44](https://cloud.githubusercontent.com/assets/528072/24525696/f39405be-1560-11e7-840a-a768c829ab6c.png)

Ref: sagemathinc/smc/issues/1731

**Comment by bgschiller** [comment]
Thanks for posting this. I suspect it's crashing on those unicode characters.

I'll try and take a look at this when I have time, but it's not a project I'm very active on. Anyone reading this is welcome to take a stab at it.

ps, sorry about the slow response, I was somehow not getting notifications of these issues.

**Comment by mhoangvslev** [comment]
Should be cool now with latest commit

**Comment by bgschiller** [comment]
This seems to be fixed now. I didn't do anything to make it so, but I did install with python3. I'm guessing the str/bytes change took care of it.
