### ISSUE TITLE
unable to connect with localhost

### ISSUE THREAD

**Issue by mythical-programmer** [bgschiller/postgres_kernel#5]
I am getting this error and kernel is always restarting.

```
(::1) 15.17ms referer=http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=postgres
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3: Error while finding spec for 'postgres_kernel.__main__' (<class 'ImportError'>: No module named 'version'); 'postgres_kernel' is a package and cannot be directly executed
```

**Comment by bgschiller** [comment]
I suspect this is specific to python 3. I didn't test python3 while developing.

I'll try and take a look at this when I have time, but it's not a project I'm very active on. Anyone reading this is welcome to take a stab at it.

ps, sorry about the slow response, I was somehow not getting notifications of these issues.

**Comment by bgschiller** [comment]
Tested and working with localhost, python3 in version 0.2.1
