### ISSUE TITLE
Being able to set autocommit

### ISSUE THREAD

**Issue by BertrandBordage** [bgschiller/postgres_kernel#7]
It would be nice to have a way to set the autocommit status as well as other similar settings.
By default, autocommit is disabled, which may be very misleading to database beginners.

**Comment by bgschiller** [comment]
@BertrandBordage I completely agree. I'll work on something soon and release it.

(Apologies for the slow response-- I mistakenly had email notifications turned off. Fixed now)

**Comment by bgschiller** [comment]
This is now fixed and available in 0.2.1!
